# This file is passed by trainer-cli to scripts/ips-txt-to-html.py

name: Advanced Docker Orchestration
repo: https://github.com/jpetazzo/orchestration-workshop

instance_login: docker
instance_password: training

clustersize: 2  # Number of VMs per cluster
pagesize: 15    # Number of cards to print per page

background_image: https://myapps.developer.ubuntu.com/site_media/appmedia/2014/12/swarm.png
#background_image: ../media/swarm.png

# To be printed on the cards:
blurb: >
    Here is the connection information to your very own 
       cluster for this orchestration workshop. You can connect 
       to each VM with any SSH client.

       Your machines are:

# {url} will be replaced by the script
footer: >
    <p>For slides, chat and other useful links, see: </p>
    <center>{url}</center>

url: http://container.training/
